#!/usr/bin/env python3
"""
Per-frame speech track for the pixel avatar, from a voiceover WAV.

For every video frame it decides:
  viseme  rest | a1 a2 a3 (open "ah") | e1 e2 (wide "ee") | o1 o2 (round "oo")
  bob     1 on stressed syllable onsets (a one-pixel nod), else 0
  brow    1 around the few strongest emphasis peaks, else 0

How: loudness (RMS) sets how open the mouth is, smoothed with a fast attack
and slower release so it eases instead of snapping; spectral brightness
(centroid) picks the shape family — bright → "ee", dark → "oo", middle → "ah";
sharp dips between syllables force a brief close (m/b/p feel); a 3-frame
majority filter removes single-frame flicker.

Usage: lipsync.py <voiceover.wav> <out.json|out.ts> [fps=30]
       (.ts writes a module exporting LIPSYNC, ready to import in Remotion)
Run with the OpenVoice venv Python (numpy).
"""
import json, subprocess, sys
import numpy as np

src, out = sys.argv[1], sys.argv[2]
FPS = int(sys.argv[3]) if len(sys.argv) > 3 else 30
SR = 16000
raw = subprocess.run(["ffmpeg", "-v", "error", "-i", src, "-ac", "1", "-ar", str(SR), "-f", "s16le", "-"],
                     capture_output=True, check=True).stdout
x = np.frombuffer(raw, np.int16).astype(np.float32) / 32768
hop = SR // FPS
n = len(x) // hop
win = np.hanning(hop * 2)
freqs = np.fft.rfftfreq(hop * 2, 1 / SR)
band = (freqs > 250) & (freqs < 4000)

rms, cent = np.zeros(n), np.zeros(n)
for i in range(n):
    seg = x[max(0, i * hop - hop // 2): i * hop - hop // 2 + hop * 2]
    if len(seg) < hop * 2:
        seg = np.pad(seg, (0, hop * 2 - len(seg)))
    rms[i] = np.sqrt(np.mean(seg ** 2))
    mag = np.abs(np.fft.rfft(seg * win))[band]
    cent[i] = (freqs[band] * mag).sum() / (mag.sum() + 1e-9)

db = 20 * np.log10(np.maximum(rms, 1e-5))
floor = np.percentile(db, 15)
speech = db > floor + 8
# openness relative to the other *spoken* frames, plus syllable contrast vs a ~0.4s local max,
# so a compressed voiceover still uses the full closed→wide range
lo, hi = np.percentile(db[speech], [10, 92]) if speech.any() else (floor, db.max())
rel = np.clip((db - lo) / (hi - lo + 1e-9), 0, 1)
k = int(FPS * 0.4)
local_max = np.array([db[max(0, i - k): i + k + 1].max() for i in range(n)])
syl = np.clip(1 - (local_max - db) / 12, 0, 1)
level = np.where(speech, 0.55 * rel + 0.45 * syl, 0) * np.clip((db - floor) / 8, 0, 1)

# ease: fast attack, slower release
env = np.zeros(n)
for i in range(n):
    prev = env[i - 1] if i else 0
    k = 0.7 if level[i] > prev else 0.4
    env[i] = prev + (level[i] - prev) * k

voiced = env > 0.14
c_lo, c_hi = (np.percentile(cent[voiced], [16, 82]) if voiced.any() else (900, 1800))

vis = []
for i in range(n):
    e = env[i]
    if not voiced[i]:
        vis.append("rest"); continue
    if cent[i] >= c_hi:
        vis.append("e1" if e < 0.72 else "e2")
    elif cent[i] <= c_lo:
        vis.append("o1" if e < 0.72 else "o2")
    else:
        vis.append("a1" if e < 0.5 else "a2" if e < 0.8 else "a3")

# brief closures on sharp dips between syllables (m / b / p)
for i in range(1, n - 1):
    if level[i] < 0.55 * max(level[i - 1], level[i + 1]) and level[i] < 0.45:
        vis[i] = "rest"

# 3-frame majority filter → no single-frame flicker
clean = vis[:]
for i in range(1, n - 1):
    if vis[i] != vis[i - 1] and vis[i] != vis[i + 1] and vis[i - 1] == vis[i + 1]:
        clean[i] = vis[i - 1]
vis = clean

# ease between openness levels: never jump more than one step in a single frame
LEVEL = {"rest": 0, "a1": 1, "e1": 1, "o1": 1, "a2": 2, "e2": 2, "o2": 2, "a3": 3}
def step_down(v):
    return {"a3": "a2", "a2": "a1", "e2": "e1", "o2": "o1"}.get(v, v)
for i in range(1, n):
    prev, cur = vis[i - 1], vis[i]
    if LEVEL[cur] - LEVEL[prev] >= 2:          # opening fast → pass through a smaller shape
        vis[i] = cur[0] + "1" if cur != "rest" else cur
    elif LEVEL[prev] - LEVEL[cur] >= 2:        # closing fast → half-close first
        vis[i] = step_down(prev) if LEVEL[step_down(prev)] < LEVEL[prev] else prev[0] + "1"

# nods on stressed onsets, brow raise on the strongest peaks
bob = [0] * n
last = -99
for i in range(2, n):
    if env[i] - env[i - 2] > 0.4 and i - last > 10:     # stressed onset, max ~3 nods/sec
        last = i
        for j in range(i, min(n, i + 4)):
            bob[j] = 1
brow = [0] * n
peaks = [i for i in range(1, n - 1) if env[i] >= env[i - 1] and env[i] > env[i + 1] and env[i] > 0.8]
chosen = []
for p in sorted(peaks, key=lambda i: -env[i]):
    if all(abs(p - q) > FPS * 3 for q in chosen):
        chosen.append(p)
    if len(chosen) >= max(1, n // (FPS * 5)):
        break
for p in chosen:
    for j in range(max(0, p - 3), min(n, p + 14)):
        brow[j] = 1

track = {"fps": FPS, "visemes": vis, "bob": bob, "brow": brow}
if out.endswith(".ts"):
    open(out, "w").write(f"// Generated by ~/reel-rig/avatar/lipsync.py from {src}\n"
                         "export const LIPSYNC: { fps: number; visemes: string[]; bob: number[]; brow: number[] } = "
                         + json.dumps(track) + ";\n")
else:
    json.dump(track, open(out, "w"))
from collections import Counter
print(n, "frames:", dict(Counter(vis)), "| nods:", sum(bob), "| brow frames:", sum(brow))
